version: '3'
services:
  app:
    build:
      context: ./practice9
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: charts
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  python:
    build: ./rschir
    command: python manage.py runserver
    ports:
      - "8000:8000"
    depends_on:
      - mysql    
