# Generated by Django 4.2.7 on 2023-11-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chartId', models.AutoField(primary_key=True, serialize=False)),
                ('chartName', models.CharField(max_length=1000, unique=True)),
                ('image', models.ImageField(upload_to='charts/')),
            ],
        ),
    ]
